version: "2"
services:
  ngnix_1:
    build: .
    ports:
    - "443:443"
    - "80:80"
    links:
      - backend
  backend:
    image: linoproject/web_apachephp_mysql
    volumes:
      - /Users/jan/ownCloud/DockerImages/images/compose/ngnix-ssl-sym/test:/var/www/html/
